language: python

install:
    - pip install -r requirements.txt
    - sudo apt-get install pandoc

script:
    - make generate_pdf
    - make generate_index

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: output
    target_branch: gh-pages
    on:
        branch: ci
